<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Booking;
use App\Models\PaymentSlip;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FixMissingPaymentSlips extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bookings:fix-missing-slips';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Find bookings with remaining balance that have no valid payment slip and create one for the treasurer';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Scanning for bookings with remaining balance and missing/corrupted payment slips...');
        $this->newLine();

        $fixedCount = 0;

        // Find all bookings with remaining balance (any active status)
        $bookings = DB::connection('facilities_db')
            ->table('bookings')
            ->whereIn('status', ['staff_verified', 'paid', 'pending', 'payment_pending'])
            ->where('amount_remaining', '>', 0)
            ->get();

        $this->info("Found {$bookings->count()} booking(s) with remaining balance.");
        $this->newLine();

        foreach ($bookings as $booking) {
            // Check if this booking has a valid payment slip with status 'unpaid'
            $existingSlip = DB::connection('facilities_db')
                ->table('payment_slips')
                ->where('booking_id', $booking->id)
                ->first();

            if ($existingSlip) {
                // Check if the slip has a valid status
                if (in_array($existingSlip->status, ['unpaid', 'paid', 'expired'])) {
                    $this->line("  Booking #{$booking->id}: Already has valid payment slip #{$existingSlip->id} (status: {$existingSlip->status}) - SKIPPED");
                    continue;
                }

                // Corrupted slip — fix the status
                DB::connection('facilities_db')
                    ->table('payment_slips')
                    ->where('id', $existingSlip->id)
                    ->update(['status' => 'unpaid']);

                $this->warn("  Booking #{$booking->id}: Fixed corrupted payment slip #{$existingSlip->id} (was: '{$existingSlip->status}' -> now: 'unpaid')");
                $fixedCount++;
            } else {
                // No payment slip exists — create one
                $now = Carbon::now();
                $deadline = $now->copy()->addDays(7);

                $slipNumber = PaymentSlip::generateSlipNumber();

                DB::connection('facilities_db')
                    ->table('payment_slips')
                    ->insert([
                        'slip_number' => $slipNumber,
                        'booking_id' => $booking->id,
                        'amount_due' => $booking->total_amount,
                        'payment_deadline' => $deadline,
                        'status' => 'unpaid',
                        'payment_method' => $booking->payment_method ?? 'cash',
                        'paid_at' => $booking->down_payment_paid_at,
                        'notes' => 'Down payment (' . ($booking->payment_tier ?? '?') . '%) collected at booking. Remaining: ₱' . number_format($booking->amount_remaining, 2) . ' (auto-generated by fix command)',
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]);

                $citizenName = $booking->applicant_name ?? $booking->user_name ?? 'N/A';
                $this->warn("  Booking #{$booking->id} ({$citizenName}): Created payment slip {$slipNumber}");
                $this->line("    Total: ₱" . number_format($booking->total_amount, 2) . " | Paid: ₱" . number_format($booking->amount_paid, 2) . " | Remaining: ₱" . number_format($booking->amount_remaining, 2));
                $fixedCount++;
            }
        }

        $this->newLine();
        if ($fixedCount > 0) {
            $this->info("SUCCESS: Fixed {$fixedCount} booking(s). They should now appear in the treasurer's queue.");
        } else {
            $this->info("No issues found. All bookings with remaining balance have valid payment slips.");
        }

        return Command::SUCCESS;
    }
}
