-- =============================================
-- BLOCK 1: FAQ Categories
-- Run this FIRST on the auth_db database (NOT faci_facilities)
-- =============================================

INSERT INTO `faq_categories` (`name`, `slug`, `description`, `icon`, `sort_order`, `is_active`, `created_by`, `created_at`, `updated_at`) VALUES
('Facility Reservations', 'facility-reservations', 'Questions about booking and reserving public facilities', 'calendar', 1, 1, 1, NOW(), NOW()),
('Payments & Fees', 'payments-fees', 'Information about payment methods, fees, and billing', 'credit-card', 2, 1, 1, NOW(), NOW()),
('Account Management', 'account-management', 'Help with your account settings and profile', 'user', 3, 1, 1, NOW(), NOW()),
('Cancellations & Refunds', 'cancellations-refunds', 'Policies and procedures for cancellations and refund requests', 'rotate-ccw', 4, 1, 1, NOW(), NOW()),
('Facility Guidelines', 'facility-guidelines', 'Rules, regulations, and usage guidelines for public facilities', 'book-open', 5, 1, 1, NOW(), NOW());


-- =============================================
-- BLOCK 2: FAQs
-- Run this AFTER Block 1
-- =============================================

SET @cat_reservations = (SELECT id FROM faq_categories WHERE slug = 'facility-reservations');
SET @cat_payments = (SELECT id FROM faq_categories WHERE slug = 'payments-fees');
SET @cat_account = (SELECT id FROM faq_categories WHERE slug = 'account-management');
SET @cat_cancellations = (SELECT id FROM faq_categories WHERE slug = 'cancellations-refunds');
SET @cat_guidelines = (SELECT id FROM faq_categories WHERE slug = 'facility-guidelines');

INSERT INTO `faqs` (`category_id`, `question`, `answer`, `sort_order`, `is_published`, `view_count`, `helpful_count`, `created_by`, `created_at`, `updated_at`) VALUES
(@cat_reservations, 'How do I reserve a public facility?', 'To reserve a facility, log in to your account and navigate to the Browse Facilities page. Select your preferred facility, choose an available date and time slot, fill out the booking form with the required details, and submit your reservation request. Your booking will be reviewed by staff before confirmation.', 1, 1, 45, 12, 1, NOW(), NOW()),
(@cat_reservations, 'How far in advance can I book a facility?', 'You may submit a reservation request up to 90 days in advance. We recommend booking at least 2 weeks ahead for large events to ensure availability and allow sufficient time for staff verification and document processing.', 2, 1, 32, 8, 1, NOW(), NOW()),
(@cat_reservations, 'What documents do I need to submit with my reservation?', 'You will need to provide a valid government-issued ID (front and back), a selfie with your ID for identity verification, and any supporting documents relevant to your event. For senior citizens, PWDs, or solo parents, please upload your corresponding discount ID for applicable rate reductions.', 3, 1, 28, 10, 1, NOW(), NOW()),
(@cat_reservations, 'How long does it take for my reservation to be approved?', 'After submission, your booking undergoes staff verification within 1 to 3 business days. Once verified, you will receive a notification with your payment slip and instructions. After payment is confirmed by the City Treasurer Office, your booking status will be updated to Confirmed.', 4, 1, 38, 14, 1, NOW(), NOW()),
(@cat_reservations, 'Can I reserve multiple facilities for the same event?', 'Yes, you may submit separate reservation requests for different facilities. Each booking is processed independently. Please ensure the schedules do not conflict and that each booking meets the respective facility requirements.', 5, 1, 15, 5, 1, NOW(), NOW()),
(@cat_payments, 'What are the accepted payment methods?', 'We accept payments through GCash, Maya (PayMaya), bank transfer, and over-the-counter payment at the City Treasurer Office (CTO). You will receive detailed payment instructions along with your payment slip after your booking has been verified by staff.', 1, 1, 52, 18, 1, NOW(), NOW()),
(@cat_payments, 'How much does it cost to reserve a facility?', 'Rental rates vary depending on the facility, duration, and any additional equipment requested. City residents receive a discounted rate. You can view the specific rates on each facility detail page before submitting your booking. The total amount, including any applicable discounts, will be reflected on your payment slip.', 2, 1, 41, 11, 1, NOW(), NOW()),
(@cat_payments, 'What is the payment deadline after my booking is verified?', 'You must complete payment within 72 hours (3 days) after receiving your payment slip. If payment is not received within this period, your reservation will automatically expire and the time slot will be released for other applicants.', 3, 1, 36, 9, 1, NOW(), NOW()),
(@cat_payments, 'Do residents receive a discount on facility rentals?', 'Yes, registered residents of the city are eligible for a resident discount on facility rental fees. Additionally, senior citizens, persons with disabilities (PWDs), and solo parents may qualify for further discounts upon presentation of a valid discount ID during the booking process.', 4, 1, 22, 7, 1, NOW(), NOW()),
(@cat_account, 'How do I create an account?', 'You can sign up using your Google account through our secure authentication system. Simply click Sign in with Google on the login page, and your account will be created automatically. Your name and email address will be imported from your Google profile.', 1, 1, 60, 20, 1, NOW(), NOW()),
(@cat_account, 'How can I update my profile information?', 'Navigate to the Profile section from the sidebar menu. You can update your contact number, address, and other personal details. Some information linked to your Google account (such as your name and email) may require changes through your Google account settings.', 2, 1, 18, 6, 1, NOW(), NOW()),
(@cat_account, 'How do I check my booking history?', 'Go to Transaction History in the sidebar to view all your past and current reservations. You can filter bookings by status (pending, confirmed, completed, etc.) and view details such as payment receipts, booking references, and facility information.', 3, 1, 25, 8, 1, NOW(), NOW()),
(@cat_cancellations, 'Can I cancel my reservation?', 'Yes, you may request cancellation of your booking. However, please note that cancellations made after payment verification may be subject to the city refund policy. Contact the facility management office or submit a cancellation request through your booking details page.', 1, 1, 30, 10, 1, NOW(), NOW()),
(@cat_cancellations, 'How do I request a refund?', 'If your booking is eligible for a refund, a refund request will be automatically generated upon cancellation or rejection. You will be asked to select your preferred refund method (GCash, bank transfer, or over-the-counter). Refund processing typically takes 5 to 10 business days depending on the selected method.', 2, 1, 27, 9, 1, NOW(), NOW()),
(@cat_cancellations, 'What happens if my booking is rejected?', 'If your booking is rejected during the verification process, you will receive a notification explaining the reason. Common reasons include incomplete documentation, schedule conflicts, or facility unavailability. If you have already made payment, you will be eligible for a full refund.', 3, 1, 19, 6, 1, NOW(), NOW()),
(@cat_guidelines, 'What are the general rules for using public facilities?', 'All facility users must adhere to the following: arrive on time for your scheduled reservation, maintain cleanliness and orderliness, avoid bringing prohibited items (alcoholic beverages, hazardous materials), comply with the maximum capacity limit, and vacate the premises by the end of your reserved time slot. Any damage to the facility or equipment may result in additional charges.', 1, 1, 35, 12, 1, NOW(), NOW()),
(@cat_guidelines, 'Can I bring my own equipment to the facility?', 'Yes, you may bring your own equipment such as sound systems, projectors, or decorations. However, all equipment must be declared during the booking process and is subject to staff approval. Electrical equipment must be in good working condition to prevent safety hazards.', 2, 1, 14, 4, 1, NOW(), NOW()),
(@cat_guidelines, 'Is there available parking at the facilities?', 'Parking availability varies by facility. Most large venues such as the Main Conference Hall and Sports Complex have designated parking areas. Please check the specific facility details page for parking information. We recommend carpooling or using public transportation for events with large attendance.', 3, 1, 20, 7, 1, NOW(), NOW());


-- =============================================
-- BLOCK 3: Help Articles
-- =============================================

INSERT INTO `help_articles` (`title`, `slug`, `excerpt`, `content`, `category`, `sort_order`, `is_published`, `view_count`, `helpful_count`, `tags`, `created_by`, `created_at`, `updated_at`) VALUES
('Getting Started: How to Reserve a Public Facility', 'getting-started-reserve-facility', 'A step-by-step guide to creating your first facility reservation through the online booking system.', '<h2>Step 1: Sign In to Your Account</h2><p>Visit the facility reservation portal and sign in using your Google account. If you are a first-time user, your account will be created automatically upon login.</p><h2>Step 2: Browse Available Facilities</h2><p>Navigate to the Browse Facilities page from the sidebar. You can view all available facilities along with photos, amenities, pricing, and available time slots.</p><h2>Step 3: Select a Facility and Time Slot</h2><p>Click on your preferred facility to view its details. Select your desired date and time slot from the availability calendar.</p><h2>Step 4: Complete the Booking Form</h2><p>Fill in the required information including event name, purpose, expected number of attendees, and any special requests. Upload the required documents: a valid government ID (front and back) and a selfie with your ID.</p><h2>Step 5: Review and Submit</h2><p>Review all your booking details, including the estimated total amount. Once submitted, your reservation will be queued for staff verification.</p><h2>Step 6: Make Payment</h2><p>After staff verification, you will receive a payment slip with the exact amount due and payment instructions. Complete payment within 72 hours.</p><h2>Step 7: Booking Confirmed</h2><p>Once your payment has been verified by the City Treasurer Office, your booking status will be updated to Confirmed and you will receive an official receipt via email notification.</p>', 'booking', 1, 1, 78, 25, '["reservation","booking","guide","getting started"]', 1, NOW(), NOW()),
('Understanding Payment Methods and Procedures', 'payment-methods-procedures', 'Learn about the different payment options available and how to complete your facility rental payment.', '<h2>Accepted Payment Methods</h2><p>The facility reservation system supports multiple payment channels:</p><ul><li><strong>GCash</strong> - Send payment to the designated GCash number provided on your payment slip.</li><li><strong>Maya (PayMaya)</strong> - Transfer to the official Maya account listed on your payment slip.</li><li><strong>Bank Transfer</strong> - Deposit to the city government official bank account.</li><li><strong>Over-the-Counter (CTO)</strong> - Visit the City Treasurer Office during business hours (Monday to Friday, 8:00 AM to 5:00 PM).</li></ul><h2>Payment Timeline</h2><p>After your booking is verified by staff, you will have 72 hours to complete payment. A reminder notification will be sent 24 hours and 6 hours before the deadline.</p><h2>Payment Verification</h2><p>For cashless payments, the City Treasurer Office will verify your payment within 1 to 2 business days. Once verified, an Official Receipt (OR) will be issued and you will be notified via email and in-app notification.</p>', 'payment', 2, 1, 54, 17, '["payment","gcash","maya","bank transfer","fees"]', 1, NOW(), NOW()),
('How to Check Facility Availability Using the Calendar', 'check-facility-availability-calendar', 'Use the calendar view to find open time slots and plan your reservation around existing bookings.', '<h2>Accessing the Calendar View</h2><p>From the sidebar, click on Calendar View under the Booking Management section. This displays a monthly overview of all facility bookings across all venues.</p><h2>Filtering by Facility</h2><p>Use the facility filter dropdown at the top of the calendar to narrow down the view to a specific venue.</p><h2>Reading the Calendar</h2><p>Color-coded events indicate different booking statuses:</p><ul><li><strong>Green</strong> - Confirmed bookings</li><li><strong>Yellow</strong> - Pending or under review</li><li><strong>Red</strong> - Rejected or cancelled</li><li><strong>Blue</strong> - Staff verified, awaiting payment</li></ul><h2>Checking Available Slots</h2><p>Click on any date to see the detailed schedule for that day. Available time slots will be clearly indicated.</p>', 'booking', 3, 1, 33, 11, '["calendar","availability","schedule","booking"]', 1, NOW(), NOW()),
('Managing Your Account and Profile Settings', 'managing-account-profile', 'Learn how to update your personal information, view transaction history, and manage notification preferences.', '<h2>Updating Personal Information</h2><p>Navigate to Profile in the sidebar to access your account settings. You can update your contact number, address, and other personal details.</p><h2>Viewing Transaction History</h2><p>Access Transaction History to see a complete record of all your bookings, including current status, payment details, and booking references.</p><h2>Payment History</h2><p>Under Payment Methods, you can view all your payment transactions, including payment slips, official receipts, and refund records.</p><h2>Managing Notifications</h2><p>The notification bell icon in the top navigation bar shows your recent notifications. Click on any notification to view details.</p>', 'account', 4, 1, 22, 8, '["account","profile","settings","notifications"]', 1, NOW(), NOW()),
('Cancellation and Refund Policies', 'cancellation-refund-policies', 'Understand the city cancellation procedures and how refunds are processed for facility reservations.', '<h2>Cancellation Policy</h2><p>Reservations may be cancelled at any point before the scheduled event date. The refund amount depends on when the cancellation is made:</p><ul><li><strong>Before payment verification</strong> - Full refund, no processing required.</li><li><strong>After payment verification, 7+ days before event</strong> - Full refund of the rental fee.</li><li><strong>After payment verification, less than 7 days before event</strong> - Subject to review by the facility management office.</li></ul><h2>How to Request a Cancellation</h2><p>Go to your booking details page and click Request Cancellation. Provide a reason for the cancellation.</p><h2>Refund Methods</h2><p>Available refund methods include GCash, bank transfer, and over-the-counter collection at the City Treasurer Office. Refunds are typically processed within 5 to 10 business days after approval.</p><h2>Tracking Your Refund</h2><p>You can track the status of your refund request under My Refunds in the sidebar.</p>', 'facility_info', 5, 1, 40, 13, '["cancellation","refund","policy","guidelines"]', 1, NOW(), NOW()),
('Troubleshooting Common Booking Issues', 'troubleshooting-booking-issues', 'Solutions for common problems encountered during the reservation process.', '<h2>I Cannot See Available Time Slots</h2><p>If no time slots appear for your selected date, the facility may be fully booked or under maintenance. Try selecting a different date or check the bulletin board for any scheduled maintenance announcements.</p><h2>My Booking Was Rejected</h2><p>Bookings may be rejected due to incomplete documentation, schedule conflicts, or policy violations. Check the rejection reason in your notification and resubmit with the corrected information.</p><h2>I Did Not Receive My Payment Slip</h2><p>Payment slips are generated after staff verification. Check your notifications and email (including spam folder).</p><h2>My Payment Was Not Verified</h2><p>Payment verification by the City Treasurer Office may take 1 to 2 business days. Ensure your payment reference matches the details on your payment slip.</p>', 'troubleshooting', 6, 1, 29, 9, '["troubleshooting","issues","help","problems"]', 1, NOW(), NOW());


-- =============================================
-- BLOCK 4: News Articles
-- =============================================

INSERT INTO `news` (`title`, `slug`, `excerpt`, `content`, `category`, `is_published`, `is_featured`, `is_urgent`, `view_count`, `tags`, `published_at`, `created_by`, `created_at`, `updated_at`) VALUES
('Online Facility Reservation System Now Available for All Residents', 'online-facility-reservation-system-launch', 'The city government is pleased to announce the official launch of the Online Public Facility Reservation System, allowing residents to conveniently book venues through a digital platform.', '<p>The Local Government Unit is proud to introduce the Online Public Facility Reservation System, a digital platform designed to streamline the booking process for community facilities across the city.</p><h3>Key Features</h3><ul><li>Real-time facility availability and calendar view</li><li>Secure online payment through GCash, Maya, and bank transfer</li><li>Automated notifications for booking status updates</li><li>Digital payment slips and official receipts</li><li>Resident discount automatically applied for eligible users</li></ul><p>For assistance, visit the Help Center or contact the facility management office during business hours.</p>', 'general', 1, 1, 0, 120, '["launch","online booking","facilities"]', DATE_SUB(NOW(), INTERVAL 30 DAY), 1, NOW(), NOW()),
('Main Conference Hall Renovation Complete - Now Accepting Reservations', 'main-conference-hall-renovation-complete', 'The recently renovated Main Conference Hall is now open for reservations with upgraded audio-visual equipment and improved seating capacity.', '<p>We are pleased to announce that the renovation of the Main Conference Hall has been completed.</p><h3>Upgrades Include</h3><ul><li>New high-definition projector and LED display panels</li><li>Upgraded wireless microphone and sound system</li><li>Improved air conditioning units for better ventilation</li><li>Expanded seating capacity from 150 to 200 persons</li><li>Newly installed Wi-Fi access for event attendees</li></ul><p>Rental rates remain unchanged during the introductory period.</p>', 'facility_update', 1, 0, 0, 85, '["conference hall","renovation","facility update"]', DATE_SUB(NOW(), INTERVAL 15 DAY), 1, NOW(), NOW()),
('Updated Facility Rental Rates Effective January 2026', 'updated-facility-rental-rates-2026', 'Please be informed of the revised rental rates for public facilities, effective January 1, 2026, as approved by the City Council.', '<p>In accordance with City Ordinance No. 2025-089, the rental rates for public facilities have been revised effective January 1, 2026.</p><h3>Summary of Changes</h3><ul><li>Base rental rates adjusted by 5 to 10 percent depending on the facility</li><li>Resident discount maintained at the current rate</li><li>Senior citizen, PWD, and solo parent discounts remain in effect</li><li>Extension rates standardized across all venues</li><li>Equipment rental fees updated to reflect current market rates</li></ul><p>For questions regarding the rate adjustments, please contact the City Treasurer Office or visit the Help Center.</p>', 'policy_change', 1, 0, 0, 65, '["rates","policy","pricing","update"]', DATE_SUB(NOW(), INTERVAL 45 DAY), 1, NOW(), NOW()),
('Scheduled Maintenance: Sports Complex Closed February 10-14', 'sports-complex-maintenance-february-2026', 'The Sports Complex will be temporarily closed for scheduled maintenance from February 10 to 14, 2026. Existing reservations during this period will be rescheduled.', '<p>Please be advised that the Sports Complex will undergo scheduled preventive maintenance from <strong>February 10 to 14, 2026</strong>. The facility will be closed to the public during this period.</p><h3>Maintenance Activities</h3><ul><li>Floor resurfacing and repair of the indoor court</li><li>Inspection and servicing of electrical systems</li><li>Plumbing maintenance and restroom repairs</li><li>Repainting of common areas and exterior walls</li></ul><p>We apologize for any inconvenience. The facility is expected to reopen on <strong>February 15, 2026</strong>.</p>', 'maintenance', 1, 0, 1, 92, '["maintenance","sports complex","closure","schedule"]', DATE_SUB(NOW(), INTERVAL 5 DAY), 1, NOW(), NOW()),
('GCash and Maya Payments Now Accepted for Facility Reservations', 'gcash-maya-payments-accepted', 'In line with the city digital transformation initiative, cashless payment options via GCash and Maya are now available for facility rental payments.', '<p>The City Treasurer Office now accepts GCash and Maya as official payment channels for facility rental fees.</p><h3>How to Pay via GCash or Maya</h3><ol><li>Complete your booking and wait for staff verification.</li><li>Once verified, you will receive a payment slip with the GCash/Maya account details.</li><li>Send the exact amount indicated on your payment slip.</li><li>Use your booking reference number as the payment description.</li><li>The Treasurer Office will verify your payment within 1 to 2 business days.</li></ol><h3>Benefits of Cashless Payment</h3><ul><li>No need to visit the City Treasurer Office in person</li><li>Instant payment confirmation via transaction receipt</li><li>Secure and traceable digital transactions</li><li>Available 24/7 for your convenience</li></ul>', 'general', 1, 0, 0, 73, '["gcash","maya","payment","cashless","digital"]', DATE_SUB(NOW(), INTERVAL 60 DAY), 1, NOW(), NOW());
