@extends('layouts.app')

@section('title', 'Monthly Reports')

@section('content')
<div class="space-y-6">
    <div class="bg-lgu-headline rounded-2xl p-8 text-white shadow-lgu-lg overflow-hidden relative">
        <div class="absolute inset-0 opacity-10">
            <svg class="w-full h-full" viewBox="0 0 60 60" xmlns="http://www.w3.org/2000/svg">
                <pattern id="pattern" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                    <circle cx="10" cy="10" r="1" fill="currentColor"/>
                </pattern>
                <rect width="100%" height="100%" fill="url(#pattern)"/>
            </svg>
        </div>
        
        <div class="relative z-10 flex items-center justify-between">
            <div class="space-y-3">
                <div class="flex items-center space-x-3">
                    <div class="w-16 h-16 bg-lgu-highlight/20 rounded-2xl flex items-center justify-center backdrop-blur-sm border border-white/10">
                        <svg class="w-8 h-8 text-lgu-highlight" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M3 3a1 1 0 011-1h12a1 1 0 011 1v14a1 1 0 01-1 1H4a1 1 0 01-1-1V3zm2 2h10v2H5V5zm0 4h10v2H5V9zm0 4h5v2H5v-2z" clip-rule="evenodd"/>
                        </svg>
                    </div>
                    <div>
                        <h1 class="text-3xl font-bold mb-1 text-white">Monthly Reports Archive</h1>
                        <p class="text-gray-200">Review, download, and manage all facility performance reports.</p>
                    </div>
                </div>
            </div>
            <a href="{{ route('admin.monthly-reports.create') }}" 
               class="px-5 py-2.5 bg-lgu-highlight text-white font-semibold rounded-lg hover:bg-lgu-button transition-colors shadow-lg">
                <svg class="w-5 h-5 inline-block mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
                Generate Report
            </a>
        </div>
    </div>

    <div class="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
        @if($monthlyReports->count())
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Report ID
                            </th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Period
                            </th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Generated By
                            </th>
                            <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Status
                            </th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date Created
                            </th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($monthlyReports as $report)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ $report->id }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-base font-semibold text-lgu-headline">
                                    {{ \Carbon\Carbon::create()->month($report->month)->format('F') }} {{ $report->year }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                                    {{ $report->generated_by_name ?? 'System' }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-center">
                                    @php
                                        $statusClass = [
                                            'draft' => 'bg-gray-100 text-gray-800',
                                            'final' => 'bg-green-100 text-green-800 font-semibold',
                                            'archived' => 'bg-blue-100 text-blue-800',
                                        ][$report->status] ?? 'bg-yellow-100 text-yellow-800';
                                    @endphp
                                    <span class="px-3 py-1 text-xs font-medium leading-5 rounded-full {{ $statusClass }}">
                                        {{ ucfirst($report->status) }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                                    {{ $report->created_at->format('M d, Y') }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium space-x-3">
                                    <a href="{{ route('admin.monthly-reports.show', $report->id) }}" 
                                       class="text-lgu-highlight hover:text-lgu-button font-medium">View</a>
                                    
                                    @if($report->status === 'final')
                                    <a href="{{ route('admin.monthly-reports.download', $report->id) }}" 
                                       class="text-green-600 hover:text-green-800 font-medium">
                                        Download
                                    </a>
                                    @endif
                                    
                                    @if($report->status === 'draft')
                                    <a href="{{ route('admin.monthly-reports.edit', $report->id) }}" 
                                       class="text-blue-600 hover:text-blue-800 font-medium">Edit</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="px-6 py-4 border-t border-gray-200">
                {{ $monthlyReports->links() }}
            </div>
        @else
            <div class="text-center py-12">
                <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                </svg>
                <h3 class="mt-2 text-lg font-medium text-gray-900">No Monthly Reports</h3>
                <p class="mt-1 text-sm text-gray-500">Get started by generating the first monthly report.</p>
                <div class="mt-6">
                    <a href="{{ route('admin.monthly-reports.create') }}" 
                       class="inline-flex items-center px-4 py-2 bg-lgu-highlight text-white font-medium rounded-lg hover:bg-lgu-button shadow-md">
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>
                        Generate Report
                    </a>
                </div>
            </div>
        @endif
    </div>
</div>
@endsection